ipv6: add support for %iface
i3/i3status pull request #327
Opened 2018-12-26 19:38 UTC by Dettorer

This follows the discussions in #205.

One problem is that in order to determine the IPv6's interface, we need to use `getifaddrs(3)` and walk through its linked list. We could return a cached value when we query the same IPv6 address twice in a row but that's not perfect, what do you think?

2021-12-20 16:27 UTC, stapelberg commented
Sorry for the lack of feedback on this. Are you still interested in pursuing this PR?

2021-12-20 19:42 UTC, Dettorer commented
Haha I saw the ping on the corresponding issue too. I don't personally use i3status anymore but I'll be happy to help finish this! Do you already have some feedback or do you want me to try and rebase it first? (I didn't realize it's been three whole years already)

2021-12-22 08:27 UTC, stapelberg commented
> Haha I saw the ping on the corresponding issue too. I don't personally use i3status anymore but I'll be happy to help finish this! Do you already have some feedback or do you want me to try and rebase it first? (I didn't realize it's been three whole years already)

Thanks!

The overall approach (using getifaddrs) is fine, I think.

Can you rebase the commit to the current git repository contents please?

Also, can you only call the interface-finding code when actually replacing `%iface`, so that users who don’t use `%iface` don’t need to incur the extra syscall cost?

2023-01-05 18:05 UTC, Dettorer commented
Hi! Sorry for the *year* of silence, I rebased and applied your suggestion, although with the new `format_placeholders()` function I had to do an extra scan of the `format_up` string with `strstr()` to know if getting the interface name was needed.

I tested the module with and without using the placeholder, it works and the function is called only when needed, but I didn't compare the execution time to know if using `strstr()` is actually faster than the function that finds the interface name (I guess it should be, and by a lot, as long as the `format_up` string isn't absurdly large).

Let me know if this needs more tweaking or testing, it shouldn't take me a year to react this time!

2023-01-05 20:08 UTC, stapelberg requested changes

2023-01-05 20:08 UTC, stapelberg commented on src/print_ipv6_addr.c
> +        return NULL;
Returning NULL here crashes format_placeholders(), so it would be better to just unconditionally return iface_string

2023-01-05 20:08 UTC, stapelberg commented on src/print_ipv6_addr.c
> +        if (addr->ifa_addr && addr->ifa_addr->sa_family == AF_INET6) {
Invert this condition to save one level of indentation:

```c
if (addr->ifa_addr == NULL || addr->ifa_addr->sa_family != AF_INET6) {
  continue;
}
// …
```

2023-01-05 20:08 UTC, stapelberg commented on src/print_ipv6_addr.c
> +    if (searched_addr_string == NULL)
Add braces please (our style for new code always uses braces)

2023-01-05 21:23 UTC, Dettorer commented on src/print_ipv6_addr.c
> +        return NULL;
Indeed. Can I suggest something more explicit than an empty string, like "no iface found" or "missing_iface"? That would mean setting a default value for `iface_string` and returning it unconditionally. I guess I should also do that on library functions error rather than returning NULL, or return yet another string, like "error_iface" to help future debug?

2023-01-06 07:30 UTC, stapelberg commented on src/print_ipv6_addr.c
> +        return NULL;
Maybe returning `(error)` would be short enough, delimited enough (with the parenthesis), and descriptive enough?

2023-01-06 09:44 UTC, Dettorer commented
I applied the requested changes and the improved error reporting (replace the placeholder by `"(error)"` if any problem arises and print the details on stderr). I also made it so `get_iface_addr()` isn't called if the interface name placeholder is present but there is no IPv6 connectivity.

2023-01-06 21:54 UTC, Dettorer commented
I see the CI pipeline is failing because of a missing clang-format package, I ran the steps manually in the meantime.

A format issue was detected (fixed in 054833e from last force-push) and two tests don't pass (022-cpu-usage-tenth-cpu and 006-cpu-usage-max-threshold-format) but they fail on main too, it doesn't seem this is linked to this PR. Everything else (build and other tests) seems to run correctly.

2023-01-07 08:51 UTC, stapelberg commented
I pushed commit https://github.com/i3/i3status/commit/07ad5aef2deea1f10eb6c544593e7a87205f24f8, can you rebase your branch please?

2023-01-07 08:54 UTC, stapelberg commented
The tests all work on my machine (and on GitHub Actions: https://github.com/i3/i3status/actions/runs/3861330716/jobs/6582243202), both on main and with your changes.

2023-01-07 09:19 UTC, Dettorer commented
Done, and the CI does pass indeed (triggered on my fork by fast forwarding main to my branch https://github.com/Dettorer/i3status/actions/runs/3861423000)

2023-01-07 09:29 UTC, merged

2023-01-07 09:29 UTC, stapelberg commented
Thanks!