add sndio(7) support which is the only supported mixer backend on OpenBSD
i3/i3status pull request #470
Opened 2021-12-06 10:34 UTC by rnagy

This pull request adds sndio support to i3status. This is the only supported mixer backend
on OpenBSD so let's disable everything else.

2021-12-15 11:34 UTC, rnagy commented
@stapelberg

2021-12-15 12:29 UTC, stapelberg requested changes

2021-12-15 12:29 UTC, stapelberg commented on meson.build
> +if get_option('sndio')
Instead of making this feature optional, can you make it non-optional on OpenBSD please?

2021-12-15 12:29 UTC, stapelberg commented on src/sndio.c
> +    if (d == NULL)
Here and elsewhere, please add braces:

```c
if (d == NULL) {
  return;
}
```

2021-12-15 12:29 UTC, stapelberg commented on src/sndio.c
> +    struct control *next;
Any reason not to use the include/queue.h macros for this list?

2021-12-15 12:29 UTC, stapelberg commented on src/sndio.c
> +    for (c = controls;; c = c->next) {
Why not `for (c = controls; c != NULL; c = c->next)` instead of the explicit `if (c == NULL) { return }` below?

2021-12-19 10:15 UTC, rnagy commented on src/sndio.c
> +    if (d == NULL)
fixed.

2021-12-19 10:15 UTC, rnagy commented on src/sndio.c
> +    for (c = controls;; c = c->next) {
fixed

2021-12-19 10:19 UTC, rnagy commented on src/sndio.c
> +    struct control *next;
i don't see the reason why for such simple code, but doable if you insist

2021-12-19 21:32 UTC, stapelberg commented on src/sndio.c
> +    struct control *next;
It’s not really about complexity, but rather uniformity and code re-use. No need to have multiple linked list implementations within the same project… :)

2026-06-17 08:25 UTC, closed without merging